# optimizer/bench_writer.py
# Writes an optimized circuit as a proper .bench file.
#
# Output includes:
#   - Valid .bench file (parseable by ABC, Yosys, our own parser)
#   - Cost report:  original vs optimized PAC cost
#   - Gate-level diff: what changed, what was removed/added
#   - ABC CEC command printed for immediate validation
#
# Usage:
#   from optimizer.bench_writer import write_bench, write_optimization_report
#   write_bench(inputs, outputs, gates, "output/s1196_optimized.bench")

import os
import sys
from datetime import datetime
from typing import Dict, List, Tuple, Optional

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from optimizer.cost_function  import compute_pac_cost
from optimizer.mutations      import get_mutation_stats

Gates = Dict[str, Tuple[str, List[str]]]


# ─────────────────────────────────────────────────────────────
# BENCH WRITER
# ─────────────────────────────────────────────────────────────

def write_bench(inputs:    List[str],
                outputs:   List[str],
                gates:     Gates,
                filepath:  str,
                circuit_name: str = "optimized",
                comment:   str    = "") -> str:
    """
    Writes a circuit to a proper .bench file.

    Format:
        # comment header
        INPUT(signal)
        OUTPUT(signal)
        signal = GATETYPE(in1, in2, ...)

    Args:
        inputs        : list of primary input signal names
        outputs       : list of primary output signal names
        gates         : dict {signal: (gate_type, [input_signals])}
        filepath      : where to write the file
        circuit_name  : name embedded in header comment
        comment       : optional extra comment line

    Returns:
        filepath (for chaining)
    """
    os.makedirs(os.path.dirname(filepath) if os.path.dirname(filepath) else '.', exist_ok=True)

    lines = []

    # ── Header ───────────────────────────────────────────────
    lines.append(f"# {circuit_name}")
    lines.append(f"# Generated by AI-Driven Circuit Optimization System")
    lines.append(f"# Timestamp : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"# Inputs    : {len(inputs)}")
    lines.append(f"# Outputs   : {len(outputs)}")
    lines.append(f"# Gates     : {len(gates)}")
    if comment:
        lines.append(f"# {comment}")
    lines.append("")

    # ── Primary inputs ────────────────────────────────────────
    for inp in inputs:
        lines.append(f"INPUT({inp})")
    lines.append("")

    # ── Primary outputs ───────────────────────────────────────
    for out in outputs:
        lines.append(f"OUTPUT({out})")
    lines.append("")

    # ── Gate definitions ──────────────────────────────────────
    # Topological order — ensures every signal is defined before use.
    ordered = _topological_sort(inputs, gates)

    for sig in ordered:
        if sig not in gates:
            continue
        gate_type, gate_inputs = gates[sig]
        inputs_str = ", ".join(gate_inputs)
        lines.append(f"{sig} = {gate_type}({inputs_str})")

    content = "\n".join(lines) + "\n"

    with open(filepath, 'w') as f:
        f.write(content)

    return filepath


def _topological_sort(inputs: List[str], gates: Gates) -> List[str]:
    """
    Returns gate output signals in topological order.
    Ensures every signal's inputs are defined before it appears.
    Uses iterative DFS to avoid Python recursion limits on large circuits.
    """
    visited = set()
    order   = []

    # All known signals = inputs + gate outputs
    all_signals = set(inputs) | set(gates.keys())

    def dfs(sig: str):
        stack = [(sig, False)]
        in_stack = set()

        while stack:
            node, processed = stack.pop()

            if processed:
                if node in gates and node not in visited:
                    visited.add(node)
                    order.append(node)
                continue

            if node in visited or node not in gates:
                continue

            if node in in_stack:
                # Cycle detected (shouldn't happen in valid bench)
                # Add anyway to avoid infinite loop
                if node not in visited:
                    visited.add(node)
                    order.append(node)
                continue

            in_stack.add(node)
            stack.append((node, True))  # Mark for post-processing

            # Push dependencies first
            _, gate_inputs = gates[node]
            for dep in reversed(gate_inputs):
                if dep not in visited and dep in gates:
                    stack.append((dep, False))

    for sig in gates:
        if sig not in visited:
            dfs(sig)

    return order


# ─────────────────────────────────────────────────────────────
# GATE-LEVEL DIFF REPORT
# ─────────────────────────────────────────────────────────────

def format_gate_diff(original_gates: Gates,
                      optimized_gates: Gates,
                      max_lines: int = 30) -> str:
    """
    Produces a human-readable diff of what changed between circuits.
    Shows removed gates, added gates, and rewired gates.
    """
    stats  = get_mutation_stats(original_gates, optimized_gates)
    lines  = []

    lines.append("GATE-LEVEL DIFF")
    lines.append("=" * 45)
    lines.append(f"  Original gates : {stats['original_count']}")
    lines.append(f"  Optimized gates: {stats['mutated_count']}")
    lines.append(f"  Net change     : {stats['net_gate_change']:+d} gates")
    lines.append("")

    if stats['removed_signals']:
        lines.append(f"  REMOVED ({len(stats['removed_signals'])} gates):")
        for sig in stats['removed_signals'][:max_lines]:
            gt, gi = original_gates[sig]
            lines.append(f"    - {sig} = {gt}({', '.join(gi)})")
        if len(stats['removed_signals']) > max_lines:
            lines.append(f"    ... and {len(stats['removed_signals']) - max_lines} more")
        lines.append("")

    if stats['added_signals']:
        lines.append(f"  ADDED ({len(stats['added_signals'])} gates):")
        for sig in stats['added_signals'][:max_lines]:
            gt, gi = optimized_gates[sig]
            lines.append(f"    + {sig} = {gt}({', '.join(gi)})")
        if len(stats['added_signals']) > max_lines:
            lines.append(f"    ... and {len(stats['added_signals']) - max_lines} more")
        lines.append("")

    if stats['changed_signals']:
        lines.append(f"  REWIRED ({len(stats['changed_signals'])} gates):")
        for sig in stats['changed_signals'][:max_lines]:
            orig_gt, orig_gi = original_gates.get(sig, ('?', []))
            new_gt,  new_gi  = optimized_gates.get(sig, ('?', []))
            orig_str = f"{orig_gt}({', '.join(orig_gi)})"
            new_str  = f"{new_gt}({', '.join(new_gi)})"
            lines.append(f"    ~ {sig}: {orig_str}  →  {new_str}")
        if len(stats['changed_signals']) > max_lines:
            lines.append(f"    ... and {len(stats['changed_signals']) - max_lines} more")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────
# FULL OPTIMIZATION REPORT
# ─────────────────────────────────────────────────────────────

def write_optimization_report(circuit_name:    str,
                               inputs:          List[str],
                               outputs:         List[str],
                               original_gates:  Gates,
                               optimized_gates: Gates,
                               original_bench:  str,
                               optimized_bench: str,
                               optimizer_name:  str = "SA",
                               report_path:     Optional[str] = None) -> str:
    """
    Writes a full text report of the optimization run.

    Includes:
      - PAC cost comparison (original vs optimized)
      - Gate count change
      - Gate-level diff
      - ABC CEC command for external verification

    Args:
        circuit_name    : name of the circuit
        inputs          : primary inputs
        outputs         : primary outputs
        original_gates  : gates before optimization
        optimized_gates : gates after optimization
        original_bench  : path to original .bench file
        optimized_bench : path to optimized .bench file
        optimizer_name  : which optimizer was used
        report_path     : where to write report (None = print only)

    Returns:
        Report text as string
    """
    orig_cost = compute_pac_cost(original_gates,  inputs)
    opt_cost  = compute_pac_cost(optimized_gates, inputs)

    improvement = (
        (orig_cost['total_cost'] - opt_cost['total_cost'])
        / orig_cost['total_cost'] * 100
    )

    lines = []
    sep   = "=" * 55

    lines.append(sep)
    lines.append(f"  OPTIMIZATION REPORT")
    lines.append(f"  Circuit   : {circuit_name}")
    lines.append(f"  Optimizer : {optimizer_name}")
    lines.append(f"  Timestamp : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(sep)
    lines.append("")

    # ── PAC Cost comparison ───────────────────────────────────
    lines.append("PAC COST COMPARISON")
    lines.append("-" * 45)
    lines.append(f"  {'Metric':<15} {'Original':>12} {'Optimized':>12} {'Change':>10}")
    lines.append(f"  {'-'*15} {'-'*12} {'-'*12} {'-'*10}")

    for label, o_key, u_key in [
        ("Power",      'power',      'power'),
        ("Area",       'area',       'area'),
        ("WireLength", 'wirelength', 'wirelength'),
        ("TOTAL COST", 'total_cost', 'total_cost'),
    ]:
        o_val = orig_cost[o_key]
        u_val = opt_cost[u_key]
        delta = u_val - o_val
        pct   = (delta / o_val * 100) if o_val != 0 else 0
        lines.append(f"  {label:<15} {o_val:>12.4f} {u_val:>12.4f} {pct:>+9.2f}%")

    lines.append("")
    lines.append(f"  PAC Improvement : {improvement:.4f}%")
    lines.append(f"  Weights         : α=0.4 (Power)  β=0.4 (Area)  γ=0.2 (Wire)")
    lines.append("")

    # ── Gate count ────────────────────────────────────────────
    orig_n = len(original_gates)
    opt_n  = len(optimized_gates)
    lines.append("GATE COUNT")
    lines.append("-" * 45)
    lines.append(f"  Original  : {orig_n}")
    lines.append(f"  Optimized : {opt_n}")
    lines.append(f"  Reduction : {orig_n - opt_n} gates ({(orig_n - opt_n)/orig_n*100:.2f}%)")
    lines.append("")

    # ── Gate-level diff ───────────────────────────────────────
    lines.append(format_gate_diff(original_gates, optimized_gates))
    lines.append("")

    # ── ABC CEC command ───────────────────────────────────────
    lines.append("EQUIVALENCE CHECK (ABC)")
    lines.append("-" * 45)
    lines.append("  Run the following command in your ABC installation:")
    lines.append("")

    # Windows path style
    orig_abs = os.path.abspath(original_bench).replace("\\", "/")
    opt_abs  = os.path.abspath(optimized_bench).replace("\\", "/")

    lines.append(f'  abc -c "cec {orig_abs} {opt_abs}"')
    lines.append("")
    lines.append("  Expected result: Networks are equivalent.")
    lines.append("  If NOT equivalent: a mutation rule has a bug — report immediately.")
    lines.append("")
    lines.append(sep)

    report_text = "\n".join(lines)

    if report_path:
        os.makedirs(os.path.dirname(report_path) if os.path.dirname(report_path) else '.', exist_ok=True)
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report_text)

    return report_text


# ─────────────────────────────────────────────────────────────
# CONVENIENCE FUNCTION
# One call to save original + optimized + report
# ─────────────────────────────────────────────────────────────

def save_optimization_result(circuit,
                              optimized_gates: Gates,
                              optimizer_name:  str = "SA",
                              output_dir:      str = "output") -> Dict:
    """
    Saves all output files for one optimization run.

    Creates:
        output/<circuit_name>_original.bench
        output/<circuit_name>_optimized.bench
        output/<circuit_name>_report.txt

    Args:
        circuit         : Circuit object (original)
        optimized_gates : gates dict after optimization
        optimizer_name  : label for the report
        output_dir      : folder to write files into

    Returns:
        dict with file paths and key metrics
    """
    name = circuit.name
    os.makedirs(output_dir, exist_ok=True)

    original_path  = os.path.join(output_dir, f"{name}_original.bench")
    optimized_path = os.path.join(output_dir, f"{name}_optimized.bench")
    report_path    = os.path.join(output_dir, f"{name}_report.txt")

    # Write original
    write_bench(
        circuit.inputs, circuit.outputs, circuit.gates,
        original_path,
        circuit_name = f"{name}_original"
    )

    # Compute costs
    orig_cost = compute_pac_cost(circuit.gates,   circuit.inputs)
    opt_cost  = compute_pac_cost(optimized_gates, circuit.inputs)
    improvement = (
        (orig_cost['total_cost'] - opt_cost['total_cost'])
        / orig_cost['total_cost'] * 100
    )

    # Write optimized
    write_bench(
        circuit.inputs, circuit.outputs, optimized_gates,
        optimized_path,
        circuit_name = f"{name}_optimized_{optimizer_name}",
        comment      = f"PAC improvement: {improvement:.4f}%"
    )

    # Write report
    report = write_optimization_report(
        circuit_name    = name,
        inputs          = circuit.inputs,
        outputs         = circuit.outputs,
        original_gates  = circuit.gates,
        optimized_gates = optimized_gates,
        original_bench  = original_path,
        optimized_bench = optimized_path,
        optimizer_name  = optimizer_name,
        report_path     = report_path,
    )

    print(report)

    return {
        'original_bench'  : original_path,
        'optimized_bench' : optimized_path,
        'report'          : report_path,
        'original_cost'   : orig_cost['total_cost'],
        'optimized_cost'  : opt_cost['total_cost'],
        'improvement_pct' : round(improvement, 4),
        'gates_original'  : len(circuit.gates),
        'gates_optimized' : len(optimized_gates),
    }


# ─────────────────────────────────────────────────────────────
# QUICK TEST
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys, os
    sys.path.append(os.path.dirname(os.path.dirname(__file__)))

    from core.pipeline        import load_circuit
    from optimizer.mutations  import apply_safe_mutation

    print("=" * 55)
    print("  BENCH WRITER TEST")
    print("=" * 55)

    circuit, _ = load_circuit("data/benchmarks/s1196.bench")

    print(f"\nApplying safe mutations to s1196...")
    current_gates = dict(circuit.gates)

    # Apply 10 valid mutations
    for i in range(10):
        mutated = apply_safe_mutation(
            circuit.inputs, circuit.outputs, current_gates, validate=True
        )
        if mutated is not None:
            current_gates = mutated

    print(f"Original gates  : {len(circuit.gates)}")
    print(f"Optimized gates : {len(current_gates)}")

    # Save all output files
    result = save_optimization_result(
        circuit         = circuit,
        optimized_gates = current_gates,
        optimizer_name  = "safe_mutations_test",
        output_dir      = "output"
    )

    print(f"\nFiles written:")
    print(f"  Original  : {result['original_bench']}")
    print(f"  Optimized : {result['optimized_bench']}")
    print(f"  Report    : {result['report']}")
    print(f"\nRun CEC check:")
    orig  = result['original_bench'].replace('\\', '/')
    opt   = result['optimized_bench'].replace('\\', '/')
    print(f'  abc -c "cec {orig} {opt}"')