# # optimizer/bench_writer.py
# # Writes an optimized circuit as a proper .bench file.
# #
# # Output includes:
# #   - Valid .bench file (parseable by ABC, Yosys, our own parser)
# #   - Cost report:  original vs optimized PAC cost
# #   - Gate-level diff: what changed, what was removed/added
# #   - ABC CEC command printed for immediate validation
# #
# # Usage:
# #   from optimizer.bench_writer import write_bench, write_optimization_report
# #   write_bench(inputs, outputs, gates, "output/s1196_optimized.bench")

# import os
# import sys
# from datetime import datetime
# from typing import Dict, List, Tuple, Optional

# sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

# from optimizer.cost_function  import compute_pac_cost
# from optimizer.mutations      import get_mutation_stats

# Gates = Dict[str, Tuple[str, List[str]]]


# # ─────────────────────────────────────────────────────────────
# # BENCH WRITER
# # ─────────────────────────────────────────────────────────────

# def write_bench(inputs:    List[str],
#                 outputs:   List[str],
#                 gates:     Gates,
#                 filepath:  str,
#                 circuit_name: str = "optimized",
#                 comment:   str    = "") -> str:
#     """
#     Writes a circuit to a proper .bench file.

#     Format:
#         # comment header
#         INPUT(signal)
#         OUTPUT(signal)
#         signal = GATETYPE(in1, in2, ...)

#     Args:
#         inputs        : list of primary input signal names
#         outputs       : list of primary output signal names
#         gates         : dict {signal: (gate_type, [input_signals])}
#         filepath      : where to write the file
#         circuit_name  : name embedded in header comment
#         comment       : optional extra comment line

#     Returns:
#         filepath (for chaining)
#     """
#     os.makedirs(os.path.dirname(filepath) if os.path.dirname(filepath) else '.', exist_ok=True)

#     lines = []

#     # ── Header ───────────────────────────────────────────────
#     lines.append(f"# {circuit_name}")
#     lines.append(f"# Generated by AI-Driven Circuit Optimization System")
#     lines.append(f"# Timestamp : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
#     lines.append(f"# Inputs    : {len(inputs)}")
#     lines.append(f"# Outputs   : {len(outputs)}")
#     lines.append(f"# Gates     : {len(gates)}")
#     if comment:
#         lines.append(f"# {comment}")
#     lines.append("")

#     # ── Primary inputs ────────────────────────────────────────
#     for inp in inputs:
#         lines.append(f"INPUT({inp})")
#     lines.append("")

#     # ── Primary outputs ───────────────────────────────────────
#     for out in outputs:
#         lines.append(f"OUTPUT({out})")
#     lines.append("")

#     # ── Gate definitions ──────────────────────────────────────
#     # Topological order — ensures every signal is defined before use.
#     ordered = _topological_sort(inputs, gates)

#     for sig in ordered:
#         if sig not in gates:
#             continue
#         gate_type, gate_inputs = gates[sig]
#         inputs_str = ", ".join(gate_inputs)
#         lines.append(f"{sig} = {gate_type}({inputs_str})")

#     content = "\n".join(lines) + "\n"

#     with open(filepath, 'w') as f:
#         f.write(content)

#     return filepath


# def _topological_sort(inputs: List[str], gates: Gates) -> List[str]:
#     """
#     Returns gate output signals in topological order.
#     Ensures every signal's inputs are defined before it appears.
#     Uses iterative DFS to avoid Python recursion limits on large circuits.
#     """
#     visited = set()
#     order   = []

#     # All known signals = inputs + gate outputs
#     all_signals = set(inputs) | set(gates.keys())

#     def dfs(sig: str):
#         stack = [(sig, False)]
#         in_stack = set()

#         while stack:
#             node, processed = stack.pop()

#             if processed:
#                 if node in gates and node not in visited:
#                     visited.add(node)
#                     order.append(node)
#                 continue

#             if node in visited or node not in gates:
#                 continue

#             if node in in_stack:
#                 # Cycle detected (shouldn't happen in valid bench)
#                 # Add anyway to avoid infinite loop
#                 if node not in visited:
#                     visited.add(node)
#                     order.append(node)
#                 continue

#             in_stack.add(node)
#             stack.append((node, True))  # Mark for post-processing

#             # Push dependencies first
#             _, gate_inputs = gates[node]
#             for dep in reversed(gate_inputs):
#                 if dep not in visited and dep in gates:
#                     stack.append((dep, False))

#     for sig in gates:
#         if sig not in visited:
#             dfs(sig)

#     return order


# # ─────────────────────────────────────────────────────────────
# # GATE-LEVEL DIFF REPORT
# # ─────────────────────────────────────────────────────────────

# def format_gate_diff(original_gates: Gates,
#                       optimized_gates: Gates,
#                       max_lines: int = 30) -> str:
#     """
#     Produces a human-readable diff of what changed between circuits.
#     Shows removed gates, added gates, and rewired gates.
#     """
#     stats  = get_mutation_stats(original_gates, optimized_gates)
#     lines  = []

#     lines.append("GATE-LEVEL DIFF")
#     lines.append("=" * 45)
#     lines.append(f"  Original gates : {stats['original_count']}")
#     lines.append(f"  Optimized gates: {stats['mutated_count']}")
#     lines.append(f"  Net change     : {stats['net_gate_change']:+d} gates")
#     lines.append("")

#     if stats['removed_signals']:
#         lines.append(f"  REMOVED ({len(stats['removed_signals'])} gates):")
#         for sig in stats['removed_signals'][:max_lines]:
#             gt, gi = original_gates[sig]
#             lines.append(f"    - {sig} = {gt}({', '.join(gi)})")
#         if len(stats['removed_signals']) > max_lines:
#             lines.append(f"    ... and {len(stats['removed_signals']) - max_lines} more")
#         lines.append("")

#     if stats['added_signals']:
#         lines.append(f"  ADDED ({len(stats['added_signals'])} gates):")
#         for sig in stats['added_signals'][:max_lines]:
#             gt, gi = optimized_gates[sig]
#             lines.append(f"    + {sig} = {gt}({', '.join(gi)})")
#         if len(stats['added_signals']) > max_lines:
#             lines.append(f"    ... and {len(stats['added_signals']) - max_lines} more")
#         lines.append("")

#     if stats['changed_signals']:
#         lines.append(f"  REWIRED ({len(stats['changed_signals'])} gates):")
#         for sig in stats['changed_signals'][:max_lines]:
#             orig_gt, orig_gi = original_gates.get(sig, ('?', []))
#             new_gt,  new_gi  = optimized_gates.get(sig, ('?', []))
#             orig_str = f"{orig_gt}({', '.join(orig_gi)})"
#             new_str  = f"{new_gt}({', '.join(new_gi)})"
#             lines.append(f"    ~ {sig}: {orig_str}  →  {new_str}")
#         if len(stats['changed_signals']) > max_lines:
#             lines.append(f"    ... and {len(stats['changed_signals']) - max_lines} more")

#     return "\n".join(lines)


# # ─────────────────────────────────────────────────────────────
# # FULL OPTIMIZATION REPORT
# # ─────────────────────────────────────────────────────────────

# def write_optimization_report(circuit_name:    str,
#                                inputs:          List[str],
#                                outputs:         List[str],
#                                original_gates:  Gates,
#                                optimized_gates: Gates,
#                                original_bench:  str,
#                                optimized_bench: str,
#                                optimizer_name:  str = "SA",
#                                report_path:     Optional[str] = None) -> str:
#     """
#     Writes a full text report of the optimization run.

#     Includes:
#       - PAC cost comparison (original vs optimized)
#       - Gate count change
#       - Gate-level diff
#       - ABC CEC command for external verification

#     Args:
#         circuit_name    : name of the circuit
#         inputs          : primary inputs
#         outputs         : primary outputs
#         original_gates  : gates before optimization
#         optimized_gates : gates after optimization
#         original_bench  : path to original .bench file
#         optimized_bench : path to optimized .bench file
#         optimizer_name  : which optimizer was used
#         report_path     : where to write report (None = print only)

#     Returns:
#         Report text as string
#     """
#     orig_cost = compute_pac_cost(original_gates,  inputs)
#     opt_cost  = compute_pac_cost(optimized_gates, inputs)

#     improvement = (
#         (orig_cost['total_cost'] - opt_cost['total_cost'])
#         / orig_cost['total_cost'] * 100
#     )

#     lines = []
#     sep   = "=" * 55

#     lines.append(sep)
#     lines.append(f"  OPTIMIZATION REPORT")
#     lines.append(f"  Circuit   : {circuit_name}")
#     lines.append(f"  Optimizer : {optimizer_name}")
#     lines.append(f"  Timestamp : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
#     lines.append(sep)
#     lines.append("")

#     # ── PAC Cost comparison ───────────────────────────────────
#     lines.append("PAC COST COMPARISON")
#     lines.append("-" * 45)
#     lines.append(f"  {'Metric':<15} {'Original':>12} {'Optimized':>12} {'Change':>10}")
#     lines.append(f"  {'-'*15} {'-'*12} {'-'*12} {'-'*10}")

#     for label, o_key, u_key in [
#         ("Power",      'power',      'power'),
#         ("Area",       'area',       'area'),
#         ("WireLength", 'wirelength', 'wirelength'),
#         ("TOTAL COST", 'total_cost', 'total_cost'),
#     ]:
#         o_val = orig_cost[o_key]
#         u_val = opt_cost[u_key]
#         delta = u_val - o_val
#         pct   = (delta / o_val * 100) if o_val != 0 else 0
#         lines.append(f"  {label:<15} {o_val:>12.4f} {u_val:>12.4f} {pct:>+9.2f}%")

#     lines.append("")
#     lines.append(f"  PAC Improvement : {improvement:.4f}%")
#     lines.append(f"  Weights         : α=0.4 (Power)  β=0.4 (Area)  γ=0.2 (Wire)")
#     lines.append("")

#     # ── Gate count ────────────────────────────────────────────
#     orig_n = len(original_gates)
#     opt_n  = len(optimized_gates)
#     lines.append("GATE COUNT")
#     lines.append("-" * 45)
#     lines.append(f"  Original  : {orig_n}")
#     lines.append(f"  Optimized : {opt_n}")
#     lines.append(f"  Reduction : {orig_n - opt_n} gates ({(orig_n - opt_n)/orig_n*100:.2f}%)")
#     lines.append("")

#     # ── Gate-level diff ───────────────────────────────────────
#     lines.append(format_gate_diff(original_gates, optimized_gates))
#     lines.append("")

#     # ── ABC CEC command ───────────────────────────────────────
#     lines.append("EQUIVALENCE CHECK (ABC)")
#     lines.append("-" * 45)
#     lines.append("  Run the following command in your ABC installation:")
#     lines.append("")

#     # Windows path style
#     orig_abs = os.path.abspath(original_bench).replace("\\", "/")
#     opt_abs  = os.path.abspath(optimized_bench).replace("\\", "/")

#     lines.append(f'  abc -c "cec {orig_abs} {opt_abs}"')
#     lines.append("")
#     lines.append("  Expected result: Networks are equivalent.")
#     lines.append("  If NOT equivalent: a mutation rule has a bug — report immediately.")
#     lines.append("")
#     lines.append(sep)

#     report_text = "\n".join(lines)

#     if report_path:
#         os.makedirs(os.path.dirname(report_path) if os.path.dirname(report_path) else '.', exist_ok=True)
#         with open(report_path, 'w', encoding='utf-8') as f:
#             f.write(report_text)

#     return report_text


# # ─────────────────────────────────────────────────────────────
# # CONVENIENCE FUNCTION
# # One call to save original + optimized + report
# # ─────────────────────────────────────────────────────────────

# def save_optimization_result(circuit,
#                               optimized_gates: Gates,
#                               optimizer_name:  str = "SA",
#                               output_dir:      str = "output") -> Dict:
#     """
#     Saves all output files for one optimization run.

#     Creates:
#         output/<circuit_name>_original.bench
#         output/<circuit_name>_optimized.bench
#         output/<circuit_name>_report.txt

#     Args:
#         circuit         : Circuit object (original)
#         optimized_gates : gates dict after optimization
#         optimizer_name  : label for the report
#         output_dir      : folder to write files into

#     Returns:
#         dict with file paths and key metrics
#     """
#     name = circuit.name
#     os.makedirs(output_dir, exist_ok=True)

#     original_path  = os.path.join(output_dir, f"{name}_original.bench")
#     optimized_path = os.path.join(output_dir, f"{name}_optimized.bench")
#     report_path    = os.path.join(output_dir, f"{name}_report.txt")

#     # Write original
#     write_bench(
#         circuit.inputs, circuit.outputs, circuit.gates,
#         original_path,
#         circuit_name = f"{name}_original"
#     )

#     # Compute costs
#     orig_cost = compute_pac_cost(circuit.gates,   circuit.inputs)
#     opt_cost  = compute_pac_cost(optimized_gates, circuit.inputs)
#     improvement = (
#         (orig_cost['total_cost'] - opt_cost['total_cost'])
#         / orig_cost['total_cost'] * 100
#     )

#     # Write optimized
#     write_bench(
#         circuit.inputs, circuit.outputs, optimized_gates,
#         optimized_path,
#         circuit_name = f"{name}_optimized_{optimizer_name}",
#         comment      = f"PAC improvement: {improvement:.4f}%"
#     )

#     # Write report
#     report = write_optimization_report(
#         circuit_name    = name,
#         inputs          = circuit.inputs,
#         outputs         = circuit.outputs,
#         original_gates  = circuit.gates,
#         optimized_gates = optimized_gates,
#         original_bench  = original_path,
#         optimized_bench = optimized_path,
#         optimizer_name  = optimizer_name,
#         report_path     = report_path,
#     )

#     print(report)

#     return {
#         'original_bench'  : original_path,
#         'optimized_bench' : optimized_path,
#         'report'          : report_path,
#         'original_cost'   : orig_cost['total_cost'],
#         'optimized_cost'  : opt_cost['total_cost'],
#         'improvement_pct' : round(improvement, 4),
#         'gates_original'  : len(circuit.gates),
#         'gates_optimized' : len(optimized_gates),
#     }


# # ─────────────────────────────────────────────────────────────
# # QUICK TEST
# # ─────────────────────────────────────────────────────────────

# if __name__ == "__main__":
#     import sys, os
#     sys.path.append(os.path.dirname(os.path.dirname(__file__)))

#     from core.pipeline        import load_circuit
#     from optimizer.mutations  import apply_safe_mutation

#     print("=" * 55)
#     print("  BENCH WRITER TEST")
#     print("=" * 55)

#     circuit, _ = load_circuit("data/benchmarks/c2670.bench")

#     print(f"\nApplying safe mutations to s1196...")
#     current_gates = dict(circuit.gates)

#     # Apply 10 valid mutations
#     for i in range(10):
#         mutated = apply_safe_mutation(
#             circuit.inputs, circuit.outputs, current_gates, validate=True
#         )
#         if mutated is not None:
#             current_gates = mutated

#     print(f"Original gates  : {len(circuit.gates)}")
#     print(f"Optimized gates : {len(current_gates)}")

#     # Save all output files
#     result = save_optimization_result(
#         circuit         = circuit,
#         optimized_gates = current_gates,
#         optimizer_name  = "safe_mutations_test",
#         output_dir      = "output"
#     )

#     print(f"\nFiles written:")
#     print(f"  Original  : {result['original_bench']}")
#     print(f"  Optimized : {result['optimized_bench']}")
#     print(f"  Report    : {result['report']}")
#     print(f"\nRun CEC check:")
#     orig  = result['original_bench'].replace('\\', '/')
#     opt   = result['optimized_bench'].replace('\\', '/')
#     print(f'  abc -c "cec {orig} {opt}"')

# optimizer/bench_writer.py
# Writes optimized circuits as proper .bench files.
# Also produces cost reports and gate-level diffs.
#
# Output files:
#   <n>_optimized.bench   → valid .bench netlist
#   <n>_report.txt        → cost comparison + gate diff
#
# Validate with ABC:
#   abc -c "cec original.bench optimized.bench"
#   Expected: "Networks are equivalent"
#
# Usage:
#   from optimizer.bench_writer import write_bench, write_report
#   write_bench("output/s1196_optimized.bench", inputs, outputs, gates, name)
#   write_report("output/s1196_report.txt", original_circuit, optimized_result)

import os
import sys
from datetime import datetime
from typing import Dict, List, Tuple, Optional

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

Gates = Dict[str, Tuple[str, List[str]]]


# ─────────────────────────────────────────────────────────────
# BENCH FILE WRITER
# ─────────────────────────────────────────────────────────────

def write_bench(filepath: str,
                inputs: List[str],
                outputs: List[str],
                gates: Gates,
                name: str = "optimized") -> str:
    """
    Writes a valid .bench netlist file.

    Format:
        # header comment
        INPUT(signal)
        OUTPUT(signal)
        signal = GATETYPE(in1, in2, ...)

    Args:
        filepath : output file path
        inputs   : primary input signal names
        outputs  : primary output signal names
        gates    : gates dict {out_sig: (gate_type, [inputs])}
        name     : circuit name for header comment

    Returns:
        filepath (for chaining)
    """
    out_dir = os.path.dirname(filepath)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    # Build topological order so signals are defined before use
    ordered = _topological_sort(inputs, gates)

    with open(filepath, 'w',  encoding='utf-8') as f:
        # Header
        f.write(f"# {name}\n")
        f.write(f"# Generated by AI-Driven Circuit Optimizer\n")
        f.write(f"# {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"# Gates: {len(gates)}  "
                f"Inputs: {len(inputs)}  "
                f"Outputs: {len(outputs)}\n")
        f.write("#\n")

        # Primary inputs
        f.write("\n")
        for inp in inputs:
            f.write(f"INPUT({inp})\n")

        # Primary outputs
        f.write("\n")
        for out in outputs:
            f.write(f"OUTPUT({out})\n")

        # Gate definitions in topological order
        f.write("\n")
        for sig in ordered:
            if sig not in gates:
                continue
            gate_type, gate_inputs = gates[sig]
            inputs_str = ", ".join(gate_inputs)
            f.write(f"{sig} = {gate_type}({inputs_str})\n")

    return filepath


def _topological_sort(primary_inputs: List[str],
                       gates: Gates) -> List[str]:
    """
    Returns gate signal names in topological order
    (each gate appears after all its inputs are defined).
    """
    visited = set(primary_inputs)
    order   = []

    def visit(sig: str):
        if sig in visited or sig not in gates:
            return
        visited.add(sig)
        _, gate_inputs = gates[sig]
        for inp in gate_inputs:
            visit(inp)
        order.append(sig)

    for sig in gates:
        visit(sig)

    return order


# ─────────────────────────────────────────────────────────────
# COST REPORT WRITER
# ─────────────────────────────────────────────────────────────

def write_report(filepath: str,
                  original_circuit,
                  optimized_gates: Gates,
                  optimized_cost: float,
                  optimizer_name: str = "Unknown",
                  time_seconds: float = 0.0,
                  mutation_stats: Optional[Dict] = None) -> str:
    """
    Writes a human-readable optimization report.

    Includes:
        - Original vs optimized PAC cost
        - Improvement percentage
        - Gate count change
        - Gate-level diff (what was added/removed/changed)
        - Functional equivalence status

    Args:
        filepath          : output file path
        original_circuit  : Circuit object (before optimization)
        optimized_gates   : gates dict after optimization
        optimized_cost    : PAC cost of optimized circuit
        optimizer_name    : which optimizer produced this result
        time_seconds      : how long optimization took
        mutation_stats    : from get_mutation_stats() — optional

    Returns:
        filepath (for chaining)
    """
    from optimizer.cost_function import compute_pac_cost
    from optimizer.mutations     import (get_mutation_stats,
                                          validate_functional_equivalence)

    out_dir = os.path.dirname(filepath)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    orig_cost   = original_circuit.cost
    improvement = ((orig_cost - optimized_cost) / orig_cost * 100) \
                   if orig_cost else 0.0

    # Detailed cost breakdown for both
    orig_detail = compute_pac_cost(original_circuit.gates,
                                    original_circuit.inputs)
    opt_detail  = compute_pac_cost(optimized_gates,
                                    original_circuit.inputs)

    # Gate-level diff
    if mutation_stats is None:
        mutation_stats = get_mutation_stats(original_circuit.gates,
                                             optimized_gates)

    # Functional equivalence check
    is_equivalent = validate_functional_equivalence(
        original_circuit.inputs,
        original_circuit.outputs,
        original_circuit.gates,
        optimized_gates
    )

    with open(filepath, 'w', encoding='utf-8') as f:
        _write_report_content(
            f, original_circuit, optimized_gates, optimized_cost,
            orig_cost, improvement, orig_detail, opt_detail,
            mutation_stats, optimizer_name, time_seconds, is_equivalent
        )

    return filepath


def _write_report_content(f, original_circuit, optimized_gates,
                           optimized_cost, orig_cost, improvement,
                           orig_detail, opt_detail, mutation_stats,
                           optimizer_name, time_seconds, is_equivalent):
    """Writes the report content to an open file handle."""

    sep  = "=" * 60
    dash = "-" * 60

    f.write(f"{sep}\n")
    f.write(f"  AI-DRIVEN CIRCUIT OPTIMIZATION REPORT\n")
    f.write(f"{sep}\n")
    f.write(f"  Circuit    : {original_circuit.name}\n")
    f.write(f"  Optimizer  : {optimizer_name}\n")
    f.write(f"  Time       : {round(time_seconds, 3)}s\n")
    f.write(f"  Generated  : "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    f.write(f"{sep}\n\n")

    # ── Functional Correctness ────────────────────────────────
    f.write(f"  FUNCTIONAL CORRECTNESS\n")
    f.write(f"{dash}\n")
    if is_equivalent:
        status = "EQUIVALENT ✓  (safe to use)"
    else:
        status = "NOT EQUIVALENT ✗  (discard this result)"
    f.write(f"  Status     : {status}\n")
    f.write(f"  Method     : Truth-table exhaustive / sampled check\n\n")

    # ── PAC Cost Comparison ───────────────────────────────────
    f.write(f"  PAC COST COMPARISON\n")
    f.write(f"{dash}\n")
    f.write(f"  {'Metric':<20} {'Original':>12} "
            f"{'Optimized':>12} {'Change':>10}\n")
    f.write(f"  {'-'*20} {'-'*12} {'-'*12} {'-'*10}\n")

    metrics = [
        ('Power',      orig_detail['power'],     opt_detail['power']),
        ('Area',       orig_detail['area'],       opt_detail['area']),
        ('WireLength', orig_detail['wirelength'], opt_detail['wirelength']),
        ('TOTAL COST', orig_cost,                 optimized_cost),
    ]

    for label, orig_val, opt_val in metrics:
        change     = opt_val - orig_val
        change_pct = (change / orig_val * 100) if orig_val else 0
        arrow      = "↓" if change < 0 else ("↑" if change > 0 else "─")
        f.write(f"  {label:<20} {orig_val:>12.4f} {opt_val:>12.4f} "
                f"{arrow}{abs(change_pct):>8.2f}%\n")

    f.write(f"\n")
    f.write(f"  Weights    : α=0.4 (Power)  β=0.4 (Area)  "
            f"γ=0.2 (Wire)\n")
    f.write(f"  Net improvement : {round(improvement, 4)}%\n\n")

    # ── Gate Count Summary ────────────────────────────────────
    f.write(f"  GATE COUNT\n")
    f.write(f"{dash}\n")
    orig_count = mutation_stats['original_count']
    mut_count  = mutation_stats['mutated_count']
    net        = mutation_stats['net_gate_change']
    f.write(f"  Original   : {orig_count}\n")
    f.write(f"  Optimized  : {mut_count}\n")
    f.write(f"  Net change : {net:+d} gates\n\n")

    # ── Gate Type Breakdown ───────────────────────────────────
    orig_types = _count_gate_types(original_circuit.gates)
    opt_types  = _count_gate_types(optimized_gates)
    all_types  = sorted(set(orig_types) | set(opt_types))

    if all_types:
        f.write(f"  GATE TYPE BREAKDOWN\n")
        f.write(f"{dash}\n")
        f.write(f"  {'Type':<10} {'Original':>10} "
                f"{'Optimized':>10} {'Change':>8}\n")
        f.write(f"  {'-'*10} {'-'*10} {'-'*10} {'-'*8}\n")
        for gt in all_types:
            o = orig_types.get(gt, 0)
            m = opt_types.get(gt, 0)
            f.write(f"  {gt:<10} {o:>10} {m:>10} {m-o:>+8}\n")
        f.write(f"\n")

    # ── Gate-Level Diff ───────────────────────────────────────
    f.write(f"  GATE-LEVEL DIFF\n")
    f.write(f"{dash}\n")

    removed = mutation_stats['removed_signals']
    added   = mutation_stats['added_signals']
    changed = mutation_stats['changed_signals']

    if not removed and not added and not changed:
        f.write(f"  No structural changes (input reordering only)\n")
    else:
        if removed:
            f.write(f"  Removed ({len(removed)} gates):\n")
            for sig in removed[:20]:
                orig_gt, orig_gi = original_circuit.gates.get(
                    sig, ('?', []))
                f.write(f"    - {sig} = {orig_gt}"
                        f"({', '.join(orig_gi)})\n")
            if len(removed) > 20:
                f.write(f"    ... and {len(removed)-20} more\n")

        if added:
            f.write(f"\n  Added ({len(added)} gates):\n")
            for sig in added[:20]:
                opt_gt, opt_gi = optimized_gates.get(sig, ('?', []))
                f.write(f"    + {sig} = {opt_gt}"
                        f"({', '.join(opt_gi)})\n")
            if len(added) > 20:
                f.write(f"    ... and {len(added)-20} more\n")

        if changed:
            f.write(f"\n  Changed ({len(changed)} gates):\n")
            for sig in changed[:20]:
                orig_gt, orig_gi = original_circuit.gates.get(
                    sig, ('?', []))
                opt_gt,  opt_gi  = optimized_gates.get(
                    sig, ('?', []))
                f.write(f"    ~ {sig}: "
                        f"{orig_gt}({', '.join(orig_gi)}) "
                        f"→ {opt_gt}({', '.join(opt_gi)})\n")
            if len(changed) > 20:
                f.write(f"    ... and {len(changed)-20} more\n")

    f.write(f"\n")

    # ── ABC Verification Command ──────────────────────────────
    f.write(f"  VERIFICATION\n")
    f.write(f"{dash}\n")
    f.write(f"  To verify functional equivalence externally:\n\n")
    f.write(f"  ABC (recommended):\n")
    f.write(f"    abc -c \"cec {original_circuit.name}.bench "
            f"{original_circuit.name}_optimized.bench\"\n")
    f.write(f"    Expected: Networks are equivalent.\n\n")
    f.write(f"  Yosys:\n")
    f.write(f"    yosys -p \"read_bench {original_circuit.name}.bench; "
            f"read_bench {original_circuit.name}_optimized.bench; "
            f"equiv_check\"\n\n")
    f.write(f"{sep}\n")


def _count_gate_types(gates: Gates) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for _, (gt, _) in gates.items():
        counts[gt] = counts.get(gt, 0) + 1
    return counts


# ─────────────────────────────────────────────────────────────
# CONVENIENCE — write both files at once
# ─────────────────────────────────────────────────────────────

def save_optimized_circuit(output_dir: str,
                            original_circuit,
                            optimized_gates: Gates,
                            optimized_cost: float,
                            optimizer_name: str = "SA",
                            time_seconds: float = 0.0) -> Tuple[str, str]:
    """
    Saves the optimized .bench file and the text report in one call.

    Args:
        output_dir        : directory to write files into
        original_circuit  : Circuit object (before optimization)
        optimized_gates   : gates dict after optimization
        optimized_cost    : PAC cost of optimized circuit
        optimizer_name    : label for the report
        time_seconds      : optimization runtime

    Returns:
        (bench_path, report_path)
    """
    from optimizer.mutations import get_mutation_stats

    name        = original_circuit.name
    bench_path  = os.path.join(output_dir, f"{name}_optimized.bench")
    report_path = os.path.join(output_dir, f"{name}_report.txt")

    mutation_stats = get_mutation_stats(original_circuit.gates,
                                        optimized_gates)

    write_bench(
        bench_path,
        original_circuit.inputs,
        original_circuit.outputs,
        optimized_gates,
        name=f"{name}_optimized"
    )

    write_report(
        report_path,
        original_circuit,
        optimized_gates,
        optimized_cost,
        optimizer_name  = optimizer_name,
        time_seconds    = time_seconds,
        mutation_stats  = mutation_stats
    )

    return bench_path, report_path


# ─────────────────────────────────────────────────────────────
# QUICK TEST
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import time
    sys.path.append(os.path.dirname(os.path.dirname(__file__)))

    from core.pipeline       import load_circuit
    from optimizer.mutations import apply_safe_mutation

    print("=" * 55)
    print("  BENCH WRITER TEST")
    print("=" * 55)

    circuit, _ = load_circuit("data/benchmarks/s1196.bench")

    # Apply one valid mutation
    t0      = time.perf_counter()
    mutated = apply_safe_mutation(
        circuit.inputs, circuit.outputs, circuit.gates,
        max_attempts=50, validate=True
    )
    elapsed = time.perf_counter() - t0

    if mutated is None:
        print("  No valid mutation found")
        sys.exit(1)

    # Compute cost of mutated circuit
    from optimizer.cost_function import compute_pac_cost
    opt_cost = compute_pac_cost(mutated, circuit.inputs)['total_cost']

    # Write output files
    bench_path, report_path = save_optimized_circuit(
        output_dir       = "output",
        original_circuit = circuit,
        optimized_gates  = mutated,
        optimized_cost   = opt_cost,
        optimizer_name   = "SingleMutation-Test",
        time_seconds     = elapsed
    )

    print(f"  Bench file : {bench_path}")
    print(f"  Report     : {report_path}")
    print()

    # Print report to console
    with open(report_path, encoding='utf-8') as f:
        print(f.read())

    print("  Run ABC CEC to verify:")
    print(f"  abc -c \"cec data/benchmarks/s1196.bench {bench_path}\"")
    print("=" * 55)